Patch-Source: https://github.com/python-ldap/python-ldap/pull/439
From 34f8c06a8d0d02f24c6c3223619bd0511dc1d4c0 Mon Sep 17 00:00:00 2001
From: Jakub Jirutka <jakub@jirutka.cz>
Date: Tue, 2 Nov 2021 22:08:42 +0100
Subject: [PATCH] Fix wrong asserts in test_test_flags

Introduced in c5ad8025632fb5e5e84cced5a0f8c7ddda1e8dae
---
 Tests/t_cext.py | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/Tests/t_cext.py b/Tests/t_cext.py
index 816af8dd..33fbf29a 100644
--- a/Tests/t_cext.py
+++ b/Tests/t_cext.py
@@ -234,11 +234,11 @@ def test_test_flags(self):
         if 'TLS' in disabled:
             self.assertFalse(_ldap.TLS_AVAIL)
         else:
-            self.assertFalse(_ldap.TLS_AVAIL)
+            self.assertTrue(_ldap.TLS_AVAIL)
         if 'SASL' in disabled:
             self.assertFalse(_ldap.SASL_AVAIL)
         else:
-            self.assertFalse(_ldap.SASL_AVAIL)
+            self.assertTrue(_ldap.SASL_AVAIL)
 
     def test_simple_bind(self):
         l = self._open_conn()
